### ISSUE TITLE
Definir framework HTTP

### ISSUE THREAD

**Issue by wescleymatos** [softwaredobem/boraajudar-api#1]
Algumas opções:

- Express
- Hapijs

**Comment by matheusalxds** [comment]
Acho que o Express seria mais viável, já que o pessoal do curso de Fullstack utiliza bastante, então haverá várias pessoas para poder ajudar.

**Comment by tuliofaria** [comment]
Uma ideia posteriormente, é fazermos um benchmark entre as 2 ;)

**Comment by rafaleite** [comment]
São dois bons framework. Mas meu voto vai pro Express

**Comment by fernandoPerraro** [comment]
Meu voto vai pro express também.

**Comment by gilbertosil** [comment]
Também acho interessante o express, pois é uma solução com mais tempo no mercado.
